### ISSUE TITLE
Question: create user?

### ISSUE THREAD

**Issue by stadskle** [seatsio/seatsio-php#1]
I cannot find a way to create users using the SDK, is this not supported?

**Comment by mroloux** [comment]
Hi,

If you mean whether it's possible to create sub accounts through the PHP library, the answer is yes:

$client->subaccounts()->create()

Here's some more info on the concept of sub accounts: https://www.seats.io/docs/api-v2#core-resources-subaccounts

Or are you looking for a way to create top-level user accounts?

**Comment by stadskle** [comment]
Hi,

Thanks for quick reply. No I mean users: https://www.seats.io/docs/api#api-reference-users-creating-users

**Comment by stadskle** [comment]
But looking at this I might be able to use sub accounts instead, it seems like the use cases you present are almost the same. Is sub accounts your recommended approach when allowing external customers make their own charts?

**Comment by mroloux** [comment]
Yes indeed, sub accounts are intended to allow your customers to manage their own set of charts.

This PHP client is based on our new rest API (V2): https://www.seats.io/docs/api-v2 . We renamed 'user' to 'sub account' in the documentation.

**Comment by stadskle** [comment]
Ok, that looks good. Can you also confirm that the returned ID is always an integer?

**Comment by mroloux** [comment]
Indeed, sub account IDs are integers.

**Comment by stadskle** [comment]
Great, then this looks very good. Thanks.
