### ISSUE TITLE
Memory issues with eventReport -> big json

### ISSUE THREAD

**Issue by ChristianFranke** [seatsio/seatsio-php#114]
Hello seats-io team, 

unfortunately we have problems pulling reports for large event charts. Unfortunately you are using the json-decode of Guzzle from PHP in https://github.com/seatsio/seatsio-php/blob/master/src/Reports/Events/EventReports.php#L27, so we can't make any changes here. 

There are currently three solutions for us:
1. would it be possible to get the json as a string somehow? That way we could parse it ourselves using eg. https://github.com/cerbero90/lazy-json.
2. is there a plan to use pagination to get small json chunks of the event reports?
3. alternatively, we can only think of loading your reports per label, but that would mean a lot of requests (one per label), I don't think that's practicable.

Our aim is to provide our event organisers an export with all the seats (basis) and meta information (place status, buyer information, etc.). 
This works quite well at the moment (95%), but the memory limit for the remaining 5% is being hit by the `json_decode()`.

If you have a completely different solution, we would be delighted to hear it.

**Comment by mroloux** [comment]
Hi,

Our latest release (https://github.com/seatsio/seatsio-php/releases/tag/v91.7.0) switched to a more memory-efficient JSON parser. Could you try that one?

Thanks

**Comment by mroloux** [comment]
Closing this issue. Please let us know if something is still not working as expected.
