### ISSUE TITLE
extraData: add keepExtraData

### ISSUE THREAD

**Issue by ChristianFranke** [seatsio/seatsio-php#19]
Hey guys, you have kindly added the flag `keepExtraData` for `extraData` (https://docs.seats.io/docs/api-extra-data). If you have any plans when this flag will be available in this SDK (for `book()`, `release()` or `change-object-status()`), please let me know. Thanks a lot!

**Comment by mroloux** [comment]
Hi Christian, our v47 now supports the `keepExtraData` flag.
