### ISSUE TITLE
Revert back to version ranges for dependencies

### ISSUE THREAD

**Issue by hbgl** [seatsio/seatsio-php#24]
Since this is a library package, the version range for every dependency should be as broad as possible; otherwise, there will be issues when using seatsio-php together with other libraries that require different versions.

This is the commit that locked in the versions: https://github.com/seatsio/seatsio-php/commit/9233697b8eb989f6466bad7bf3a09727c03a4f3a 

Please revert back to version ranges.

**Comment by mroloux** [comment]
Hi, totally agree. We'll release a new version.

**Comment by mroloux** [comment]
Fixed in https://github.com/seatsio/seatsio-php/releases/tag/v62.4.0

Thanks for reporting this!
