### ISSUE TITLE
Upgrade netresearch/jsonmapper

### ISSUE THREAD

**Issue by stadskle** [seatsio/seatsio-php#30]
The SDK depends on an old release (2017) of netresearch/jsonmapper which is now throwing warnings in PHP 7.4, can you upgrade this for the next release?

```
Deprecated: Array and string offset access syntax with curly braces is deprecated in /vendor/netresearch/jsonmapper/src/JsonMapper.php on line 302

**Comment by mroloux** [comment]
Done in v66. Thanks!
