### ISSUE TITLE
Guzzle 7 support

### ISSUE THREAD

**Issue by alexpechkarev** [seatsio/seatsio-php#37]
Hi Team,

Thank you for fo the hard work on this Seats.io PHP client library!

Please can you look into the supporting latest Guzzle version as the current library locked to ` "guzzlehttp/guzzle": "^6.5.5"` and it's causing issues with other libraries that require a higher version of the Guzzle ?

Regards

**Comment by mroloux** [comment]
Hi!

Sure, we'll have a look at that.

**Comment by mroloux** [comment]
... our v76.0.0 now contains Guzzle 7 instead of 6.
