### ISSUE TITLE
Update sdk to work with PHP8.1 without deprecation warnings

### ISSUE THREAD

**Issue by john-happsnow** [seatsio/seatsio-php#57]
Getting deprecation warning currently for PagedIterator:
Deprecated: Return type of Seatsio\PagedIterator::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

In this case, the appropriate return types for each of the Iterator methods just need to be added.  Not sure if there are other deprecation warnings at this time.

**Comment by bverbeken** [comment]
Thanks for reporting this. 
Fixed in [v83.1.1](https://github.com/seatsio/seatsio-php/releases/tag/v83.1.1)

**Comment by john-happsnow** [comment]
Thanks for the fix!
