### ISSUE TITLE
Fix normalizeObjects

### ISSUE THREAD

**Issue by assisjeferson** [seatsio/seatsio-php#6]
Fix `normalizeObjects` to send general admission and seats in the same request 

Line `352` in `Event\Events.php`
```php
private static function normalizeObjects($objectOrObjects)  {
    ...
    return ["objectId" => $object];
    ...
}
```

to 

```php
private static function normalizeObjects($objectOrObjects)  {
    ...
    return is_array($object) ? $object : ["objectId" => $object];
    ...
}
```

**Comment by mroloux** [comment]
Hi Jeferson,

How exactly are you passing in the objects?

I've tried locally, and the following seems to work fine:

[["objectId" => "A-1"], ["objectId" => "GA1", "quantity" => 5]]
or
[new ObjectProperties("A-1"), (new ObjectProperties("GA1"))->setQuantity(5)];

**Comment by assisjeferson** [comment]
I'm passing like this

`["A-1", "A-2", ["objectId" => "GA1", "quantity" => 5]]`

**Comment by mroloux** [comment]
Oh I see, that makes sense. Made this possible in https://github.com/seatsio/seatsio-php/releases/tag/v21
