### ISSUE TITLE
Update SDK to work with php 8.2 without deprecation warnings

### ISSUE THREAD

**Issue by tectiv3** [seatsio/seatsio-php#89]
Creation of dynamic property Seatsio\SeatsioClient::$usageReports is deprecated in .../vendor/seatsio/seatsio-php/src/SeatsioClient.php on line 72

**Comment by mroloux** [comment]
Thanks, we'll have a look 👍

**Comment by mroloux** [comment]
Fixed in [v88.1.0](https://github.com/seatsio/seatsio-php/releases/tag/v88.1.0). Thanks for reporting!
